### ISSUE TITLE
Wiggle2 Bake Bone Stretching Glitch

### ISSUE THREAD

**Issue by KaijuKoder** [shteeve3d/blender-wiggle-2#68]
1. Love Wiggle2, but I'm finding when I bake (not during the real-time preview) almost every time I get glitches where, despite stretch being 0, a bone is stretched entirely through the collision body/clothes. It seems to get stuck on the other side of the body and never make it back. Unfortunately increasing precision doesn't help: It still happens.

![Wiggle2 Bone Stretching Glitch](https://github.com/user-attachments/assets/dcbeb845-c520-49fb-8702-3e4ffc123e90)

Suggestion: If stretching is set to 0, don't let the bone stretch that far. It should maintain it's original length, and if it's inside the collision body, push it back to the surface. If that's not possible, just stop it stretching and leave it inside the body, because it's easier to manually correct the animation for that instead of a bone which completely penetrates the mesh.

All that said, thanks for Wiggle2. I haven't been able to find any other way to properly do stylized hair. AFAICT Blender's new hair system can't do it.

2. When Wiggle2 works, it gives great results. The bakes are sometimes long, a couple of hours(!) (though worth it!). Here's a suggested mod to Wiggle2's bake operator so you can check progress on the console:

```
        bake_wiggle2_step = 10 # probably best a property

        first_pass = True
        for frame_begin_i in range(context.scene.frame_start, context.scene.frame_end, bake_wiggle2_step):
            frame_end_i = frame_begin_i + bake_wiggle2_step - 1
            if  frame_end_i > context.scene.frame_end:
                frame_end_i = context.scene.frame_end

            print('Wiggle2 Bake Step Begin: At {}% of Baking frames {} to {} of {} to {} '.format(
                int((frame_begin_i - context.scene.frame_start)  * 100 / (context.scene.frame_end - context.scene.frame_start)),
                frame_begin_i,
                frame_end_i,
                context.scene.frame_start,
                context.scene.frame_end
                ))

            bpy.ops.nla.bake(frame_start = frame_begin_i,
                            frame_end = frame_end_i,
                            only_selected = True,
                            visual_keying = True,
                            use_current_action = context.scene.wiggle.bake_overwrite if first_pass else True,
                            bake_types={'POSE'})

            if first_pass:            
                first_pass = False

            print('Wiggle2 Bake Step Done')

```

Feel free to use.

**Comment by KaijuKoder** [comment]
I don't know if it's related but sometimes I see stuff like this in the output:

```
Error in bpy.app.handlers.frame_change_post[0]:
Traceback (most recent call last):
  File "C:\Users\guest\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\wiggle_2.py", line 527, in wiggle_post
    move(b,dg)
  File "C:\Users\guest\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\wiggle_2.py", line 283, in move
    update_matrix(b)
  File "C:\Users\guest\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\wiggle_2.py", line 185, in update_matrix
    mat = p.wiggle.matrix @ relative_matrix(p.matrix, b.matrix)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guest\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\wiggle_2.py", line 27, in relative_matrix
    return (m2.inverted() @ m1).inverted()
            ^^^^^^^^^^^^^
ValueError: Matrix.invert(ed): matrix does not have an inverse
```
When this happens, I've found altering the accuracy or bone settings avoids it.

@shteeve3d appreciate you're busy and this addon can't be your first priority, but if you comment the script myself and others can try and fix problems such as this.

**Comment by KaijuKoder2** [comment]
Footnote: I suspect these problems are caused by failures in the collider code. Tested on a number of collider meshes and found even on relatively simple meshes the bones get stuck inside the mesh or jump through to the other side - impossibly stretching the bones in the process. Seems when a bone gets stuck inside a mesh, Wiggle 2 doesn't successfully push it or the rest of the bone chain back to the mesh surface. As https://github.com/shteeve3d/blender-wiggle-2/issues/73 mentions, using bone envelopes might help, or even just ensuring all bone head tails inside the mesh get pushed back to the mesh surface, and the lengths between them enforced.

**Comment by weThere** [comment]
Seems like it also struggles with abstracted armatures e.g., deform bones relying on an underlying mechanism (MCH) layer and control layer seen usually in generated rigs.

The best example I currently have is running wiggle on a rigify tail ("spines.simple_tail") that does not have its "follow parent" constraint set to full.

The same example but instead set as the rigify type "basic.copy_chain" and it should work fine.

**Comment by KaijuKoder2** [comment]
> The best example I currently have is running wiggle on a rigify tail ("spines.simple_tail") that does not have its "follow parent" constraint set to full.

I've found with Stylized hair if you just do the very end tips, just 1-2 bones, even if you have a possible collision near the tips, it works quite well. But if your hair chains get any longer than that, like the screenshot at the top, Wiggle 2 just can't handle it.  It goes haywire when it encounters more sophisticated bone-on-bone or bone-on-mesh collisions. It's fine for ponytails, tails, and tips of meshes, but beyond that, look elsewhere.

**Comment by LuciferTC9527** [comment]
![image](https://github.com/user-attachments/assets/1ee13532-3c86-49ef-8dd7-4496af50a610)
Remove these scale
I wasn't a big fan of wiggle2 stretch feature, so I tried removing the scaling of the bones, solving a lot of my own problems. May help with this issue

**Comment by KaijuKoder2** [comment]
Hey @LuciferTC9527! Thanks so much! You are my hero! I just tried your suggested changes and wow, it seems to be working. This came after a month of desperately and unsuccessfully trying to coax Wiggle2 into working after which I gave up after my last posts and wrote Wiggle2 off as Abandonware (which it may well still be!) Amazed that your small number of changes has such a big and positive result.

**Comment by schroef** [comment]
@KaijuKoder 

bakes of a couple hours?!?! whats that for crazy animation

**Comment by weThere** [comment]
> @KaijuKoder
> 
> bakes of a couple hours?!?! whats that for crazy animation

Bro probably making tv show or something, or running physics on every bone. Pray for Kaiju's render device.

**Comment by KaijuKoder2** [comment]
@schroef @weThere Don't pray for my GPU! Pray for my CPU!, since Wiggle2 is CPU-bound Python. But thanks to @LuciferTC9527 suggestions, Wiggle2 can bake the animated stylized hair rig pictured in OP 1020 frames in 40 minutes. Obvious Python is really really slow, but at least now it's working the results are really good.  Not Pixar good, but still good. Nothing else in the Blenderverse can do this. Spent months looking, and you can't manually animate that much hair convincingly.

With @LuciferTC9527 suggestions, the bone stretching problem has completely gone. Clear that those scale operations in the code are a bug, since I had scale turned off so shouldn't have been applied anyway. Thanks again @LuciferTC9527

**Comment by weThere** [comment]
> Nothing else in the Blenderverse can do this. Spent months looking, and you can't manually animate that much hair convincingly.

Closest I've found (costs 8$), but I miss my head physics quite a lot, although you'd think paid stuff is more consistently maintained into the future however. Python solutions are so clean though not having to add proxies and all that related overhead.
https://bartoszstyperek.gumroad.com/l/wobbly_wiggler?layout=profile

**Comment by KaijuKoder2** [comment]
> Closest I've found (costs 8$), but I miss my head physics quite a lot, although you'd think paid stuff is more consistently maintained into the future however. Python solutions are so clean though not having to add proxies and all that related overhead. https://bartoszstyperek.gumroad.com/l/wobbly_wiggler?layout=profile

Thanks to @LuciferTC9527 I have no more problems with Wiggle 2. It's working really well!

Trouble with an $8 addon is it's just enough to discourage people from using it, but not enough to financially motivate the author to maintain it. I did take a crack at writing my own Wiggle script before suggestion but never finished: it's a lot of work. For now, Wiggle 2 is it!

**Comment by weThere** [comment]
> Trouble with an $8 addon is it's just enough to discourage people from using it, but not enough to financially motivate the author to maintain it. I did take a crack at writing my own Wiggle script before suggestion but never finished: it's a lot of work. For now, Wiggle 2 is it!

Appreciate the insight. I do not really know either how big the potential buyer base of animators is and how many see the need for physics addons (of course anecdotally as a solo animator I see great effects), so I can imagine price setting must be an art as well. In either case using it as an intermediary so I get out my last batch of the year, besides there being some QoL stuff in there (a bit cleaner system for preview/pause time physics preview and custom bake frame steps (i.e., bake every x frame instead of every frame, life saver in my case of "long" 60fps scenes.)

Probably flip back to this, when I take some time to guarantee it working with latest Blender, and apply @LuciferTC9527 fixes to @schroef fork of the addon with saveable physics presets and hopefully figure out if it is possible to modify it to also allow it to bake for less frames, as having committed to almost purely IK animation the bone head physics are near invaluable in this case.

**Comment by schroef** [comment]
Wait, doesn't it show the popup for baking. I mean, it's not hard to actually allow that menu to show. We can also add a custom menu. Showing the native window is actually less work, then making a custom one. Because we then need to store all variables and do testing for it

**Comment by weThere** [comment]
> Wait, doesn't it show the popup for baking. I mean, it's not hard to actually allow that menu to show. We can also add a custom menu. Showing the native window is actually less work, then making a custom one. Because we then need to store all variables and do testing for it

That is fair if it does, spoke from memory on that, if you can set custom baking frame steps then that is an upside to wiggle2 I had forgotten was there. (if that is what was meant by the iirc "quality" slider for the physics, then again I read it has low (0) to x (high) so it wasn't intuitive to me how that would translate to frame steps to bake) I can't recall getting a popup like the native blender bake window when baking in wiggle2 6 months or so back: 
<img width="265" alt="image" src="https://github.com/user-attachments/assets/dcaf458c-b7eb-4980-984d-f71126c3f770" />

As my python writing skills at this time are especially rusty, I take your word for it being little work.

**Comment by schroef** [comment]
Indiana don't check, but the operator to bake is called, without showing the dialog, if I remember correct. We could change this so it does show a dialog. No need to bake all frames if you don't need it.

The quality is something else I believe. You sure that's just a frame step?

Edit
The quality is a iterations setting. Some settings are divided by this

**Comment by shteeve3d** [comment]
> ![image](https://private-user-images.githubusercontent.com/57080020/354837135-1ee13532-3c86-49ef-8dd7-4496af50a610.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjI1OTUsIm5iZiI6MTczNDk2MjI5NSwicGF0aCI6Ii81NzA4MDAyMC8zNTQ4MzcxMzUtMWVlMTM1MzItM2M4Ni00OWVmLThkZDctNDQ5NmFmNTBhNjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDEzNTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMzFmNjRhZmQyODdmYzEwZWI5Y2Q5YjE0OGE0YzAwMWM0YThjMTAxMWQ3NDU2YmRhNDAzYjIwMzE3ZTM3MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JvkRQ_BFlcJqKq--rshDUU_pmGNkSNjQB3a77Gge2ls) Remove these scale I wasn't a big fan of wiggle2 stretch feature, so I tried removing the scaling of the bones, solving a lot of my own problems. May help with this issue

hey! thats for looking into this!

i wouldn't want to remove scale entirely as i feel like there's plenty of applications where its a useful tool for jiggly fx. also in my experience getting proper rope physics actually needs some stretch or it doesn't work correctly (or collide correctly on longer chains).

but i agree that stretch 0 should behave as if the stretch code doesn't exist so i'll try to see if i can see if the code has obvious issues that could be fixed.

**Comment by KaijuKoder2** [comment]
_@shteeve3d> but i agree that stretch 0 should behave as if the stretch code doesn't exist so i'll try to see if i can see if the code has obvious issues that could be fixed._

Thanks Steve! (And thanks for Wiggle2!) Can confirm which the @LuciferTC9527 patch Wiggle2 can do that stylized hair rig (photo in OP) brilliantly. Without the patch, the bones somehow penetrate the body to appear on the other side. Maybe it's a collision thing, but whatever the cause the result was even though stretching was disabled (set to 0), the that bone stretched/scaled anyway.

_@weThere > Probably flip back to this, when I take some time to guarantee it working with latest Blender, and apply @LuciferTC9527 fixes to @schroef fork of the addon with saveable physics presets and hopefully figure out if it is possible to modify it to also allow it to bake for less frames, as having committed to almost purely IK animation the bone head physics are near invaluable in this case._

Did post a mod (in another issue) where splitting the bake run into smaller segments so I could track progress (% indicator, since my bakes were so long), so yes, you can bake for less frames (if that's what you mean?)

_@weThere > Appreciate the insight. I do not really know either how big the potential buyer base of animators is and how many see the need for physics addons (of course anecdotally as a solo animator I see great effects), so I can imagine price setting must be an art as well._ 

Don't know either. MeshMachine (21K sales @ $45 listened on BlenderMarker) are famously successful, but following your post I had a look at BlenderMarket and there do seem to be a lot of middling-addons doing okay (PBR Painter 1.8K sales at $30, ExteremePBR 10K sales at maybe $30). But as much as that sounds, I still wonder if all that effort is worth it. $80K a year for an IT desk job seems a much easier and safer way to make a living. Not to mention coding it in the first place. Also many addons with barely any sales at all. A bummer too that FOSS addons that keep closest to the Blender spirit like Wiggle2, and MTree, and RigACar, BakeLab2, and BlendARMocap don't get the support they deserve.

**Comment by weThere** [comment]
> Did post a mod (in another issue) where splitting the bake run into smaller segments so I could track progress (% indicator, since my bakes were so long), so yes, you can bake for less frames (if that's what you mean?)

I did struggle to find the right words here, apologise. I mean a function reduce the frame steps baked for a frame range. If you have frame range 0-120 instead of baking frame 0,1,2,3,4 etc it bakes 0,2,4,6... or further so 0,3,6,9... to make the baked action lighter and saving some clicks to reduce the action(s) after bake, as @schroef pointed out that the "quality" slider does not affect this at the baketime as it affects the iterations for the physics sim.

(A bake function you for reference find in a mocap addon like: https://github.com/Daniel-W-Blender-Python/VIPER-Blender-Mocap, it seems like entering the mocap paradigm with blender is effortful for some reason, really hoping for a live webcam to motion function appearing for latest blender as you can imagine my disappointment when stumbling across BlendAR but hitting the good old compatibility issues immediately, besides having to invest in 1 or more high fps webcams. Together with some motion triggered recording similar to how there is a audio triggered record in some audio software it could smooth the solo animation process a great deal.)

But as saint @shteeve3d has re-emerged hopefully the recent pull requests merge at least.

**Comment by KaijuKoder2** [comment]
_> I did struggle to find the right words here, apologise. I mean a function reduce the frame steps baked for a frame range. If you have frame range 0-120 instead of baking frame 0,1,2,3,4 etc it bakes 0,2,4,6... or further so 0,3,6,9... to make the baked action lighter and saving some clicks to reduce the action(s) after bake, as @schroef pointed out that the "quality" slider does not affect this at the baketime as it affects the iterations for the physics sim._

Pretty sure you can do that. If you locate the bpy.ops.nla.bake() call in Wiggle2, you can try adding a step parameter. https://docs.blender.org/api/current/bpy.ops.nla.html   And if you don't want to modify Wiggle2 directly, you can do it in a separate operator. Attach sample operator at end of this post.


Thanks for the links to [VIPER-Blender-Mocap](https://github.com/Daniel-W-Blender-Python/VIPER-Blender-Mocap)! Used to chat with the BlendARmocap author. The python library compatibility issues were a constant headache for him, and he was swamped with sometimes pretty rude support requests with nothing given in return, so totally understand his decision to move on. BlendARmocap had a lot of promise, but it required a lot of post-processing. That's also true for solutions like Rokoko. FreeMocap is still going but despite all the cameras couldn't get satisfactory results. So hand animation gives better faster results anyway, for now. Expect the tech to get there one day though, so will checkout VIPER.

```
'''
Wiggle2's bake gives no feedback, and can run for a very long time.
This modified version of it's operator gives reports.
'''
class KKOperator_bake_wiggle2(bpy.types.Operator):
    """KK - Bake Wiggle2 (reports progress in console).""" 

    bl_idname  =  'opr.object_KK_bake_wiggle2'
    bl_label   = f'KK {bl_idname}'
    bl_options = {"REGISTER", "UNDO"}

    @classmethod
    #
    def poll(cls, context):
        return  context.mode == 'POSE' and not context.object is None


    def execute(self, context):
        def push_nla():
            if context.scene.wiggle.bake_overwrite: return
            if not context.scene.wiggle.bake_nla: return
            if not context.object.animation_data: return
            if not context.object.animation_data.action: return
            action = context.object.animation_data.action
            track = context.object.animation_data.nla_tracks.new()
            track.name = action.name
            track.strips.new(action.name, int(action.frame_range[0]), action)
            
        push_nla()
        
        bpy.ops.wiggle.reset()
            
        #preroll
        duration = context.scene.frame_end - context.scene.frame_start
        preroll = context.scene.wiggle.preroll
        context.scene.wiggle.is_preroll = False
        bpy.ops.wiggle.select()
        bpy.ops.wiggle.reset()
        while preroll >= 0:
            if context.scene.wiggle.loop:
                frame = context.scene.frame_end - (preroll%duration)
                context.scene.frame_set(frame)
            else:
                context.scene.frame_set(context.scene.frame_start)
            context.scene.wiggle.is_preroll = True
            preroll -= 1
        #bake

        bake_wiggle2_step = 10

        first_pass = True
        for frame_begin_number in range(context.scene.frame_start, context.scene.frame_end, bake_wiggle2_step):
            frame_end_number = frame_begin_number + bake_wiggle2_step - 1
            if  frame_end_number > context.scene.frame_end:
                frame_end_number = context.scene.frame_end

            print('At {}% of Baking frames {} to {} of {} to {} '.format(
                int((frame_begin_number - context.scene.frame_start)  * 100 / (context.scene.frame_end - context.scene.frame_start)),
                frame_begin_number,
                frame_end_number,
                context.scene.frame_start,
                context.scene.frame_end
                ))

            bpy.ops.nla.bake(frame_start = frame_begin_number,
                            frame_end = frame_end_number,
                            only_selected = True,
                            visual_keying = True,
                            use_current_action = context.scene.wiggle.bake_overwrite if first_pass else True,
                            bake_types={'POSE'})

            if first_pass:            
                first_pass = False

            print('I: Baked!')

        
        context.scene.wiggle.is_preroll = False
        context.object.wiggle_freeze = True
        if not context.scene.wiggle.bake_overwrite:
            context.object.animation_data.action.name = 'WiggleAction'        
        return {'FINISHED'}

```

**Comment by schroef** [comment]
People, perhaps keep a issue clean of other ideas and content. This issue is going all over the place.

Perhaps it's better to call just the internal bake operator. Since people come with many custom inputs. Perhaps add more options, other wise just call the internal operator

**Comment by KaijuKoder2** [comment]
_@schroef > Perhaps it's better to call just the internal bake operator_

There's some setup you need to do before you call the internal bake operator. Thus the above operator, which is just a modified version of @shteeve3d's original operator which does that setup.

_@schroef > People, perhaps keep a issue clean of other ideas and content. This issue is going all over the place._

I'm OP and apart from integrating Lucifer's fix for it into the main trunk, this issue is nearly resolved. Please forgive the chatter. I think we're basking in the euphoria that such a big problem has been fixed. Super nice.

Can always open up a new issue for baking.
